---
title: CV

format:
  html:
    toc: true
---

## [Professional Experience]{.smallcaps}

**Agricultural Marketing Service, Dairy Program, Economics Division** <br> *Agricultural Economist* [*2022 - Present*]{style="float: right"}

As an Agricultural Economist in the Economics Division of Dairy Program, provide detailed and thoughtful economic analysis of the markets for milk and dairy products.

-   Provided extensive support to the Federal Milk Marketing Order rulemaking process, including economic analysis and subject matter expertise.
-   Lead Economics Division modeling efforts, including development and maintenance of the Dairy Program Regional Econometric Model, the Herd Size Model, Milk Production models, and the International Price model.
-   Develop monthly estimates of milk supply factors and commodity prices for the Dairy Interagency Commodity Estimates Committee, contributing to monthly World Agricultural Supply and Demand Estimates and 10-year USDA Baseline.
-   Lead support of Commodity Procurement Program by providing economic analysis, market insights, and subject matter expertise to facilitate USDA purchases of dairy products.

**University of California, Davis** <br> *Graduate Student Researcher* [*2017 - 2022*]{style="float: right"}

As a Graduate Student Researcher for Professor Daniel Sumner, analyzed growth in milk production and dairy product exports since Federal Milk Marketing Order reform and developed a model of inter-regional trade in farm milk and dairy products within the U.S.

**Congressional Budget Office** <br> *Assistant Analyst* [*2014 - 2016*]{style="float: right"}

As an Assistant Analyst in the Microeconomic Studies Division, contributed to reports on agricultural policy and energy use. Analyzed the role of reinsurance agreements in the Federal Crop Insurance Program and evaluated options to reduce the cost to the government. Assisted with reports on growing energy use in China, extraction of oil and gas on Federal lands, and government support for development of fuels and energy technologies.


## [Education]{.smallcaps}

**University of California, Davis** [**Davis, CA**]{style="float: right"} <br> *Ph.D. Agricultural and Resource Economics* [*2023*]{style="float: right"} <br> M.S. *Agricultural and Resource Economics* [*2017*]{style="float: right"}

**Washington State University** [**Pullman, WA**]{style="float: right"} <br> *B.S. Economic Sciences* [*2014*]{style="float: right"}

## [Research]{.smallcaps}

*Published Work*

Sumner, D.A., T.M. Hanon, and S. Somerville. 2021. “Effects of the COVID-19 Pandemic on the Western Dairy Industry.” Western Economics Forum 19(1):33-50. 

Sumner, D.A., T. Hanon, and W.A. Matthews. 2019. “Implication of Trade Policy Turmoil for Perennial Crops.” Choices 34(3).

Hanon, T. 2014. “The New Normal: A Policy Analysis of the US Renewable Fuel Standard.” SS-AAEA Journal of Agricultural Economics. 

*Contributions to Reports*

Matthews, W.A., D.A. Sumner, J. Medellín-Azuara, and T. Hanon. 2017. “Economics of the California Cut Flower Industry and Potential Impacts of Legal Cannabis.” University of California Agricultural Issues Center.

Congressional Budget Office. 2017. Options to Reduce the Budgetary Costs of the Federal Crop Insurance Program. Washington DC.

Congressional Budget Office. 2016. Potential Increases in Hurricane Damage in the United States: Implications for the Federal Budget. Washington DC. 

## [Awards and Recognition]{.smallcaps}

USDA Secretary's Honors [*2025*]{style="float: right"}

MRP Undersecretary's Award [*2025*]{style="float: right"}

AMS Administrator's Award [*2025*]{style="float: right"}

*Phi Beta Kappa* [*2014*]{style="float: right"}

Dairy Foods, 2nd Place Team, 5th Individual--National FFA Convention [*2009*]{style="float: right"}

## [Technical Skills]{.smallcaps}

Expertise in R Programming Language

Proficiency in Python and SAS Programming Languages

Proficiency working with Application Programming Interfaces

Proficiency in LaTeX and Quarto Typesetting and Publishing Systems

Proficiency in Microsoft Office Suite

